import streamlit as st
import json
from datetime import datetime


def render_history_download():
    if st.session_state.get("message"):
        chat_text="\n\n".join([f"{m['role'].upper()}: {m['content']}" for m in st.session_state.messages])
        st.download_botton("Download Chat History", chat_text,file_name="chat_history.txt",mime="text/plain")
        

def render_download(messages: list):
    st.markdown("### 💾 Download Chat History")

    col1, col2 = st.columns(2)

    with col1:
        st.download_button(
            label="📝 TXT",
            data=_as_txt(messages),
            file_name=f"medirag_chat_{_now()}.txt",
            mime="text/plain",
            use_container_width=True
        )

    with col2:
        st.download_button(
            label="📦 JSON",
            data=_as_json(messages),
            file_name=f"medirag_chat_{_now()}.json",
            mime="application/json",
            use_container_width=True
        )

    st.download_button(
        label="📄 Markdown Report",
        data=_as_markdown(messages),
        file_name=f"medirag_report_{_now()}.md",
        mime="text/markdown",
        use_container_width=True
    )


# ─── Formatters ───────────────────────────────────────────────────────────────

def _now() -> str:
    return datetime.now().strftime("%Y%m%d_%H%M%S")


def _as_txt(messages: list) -> str:
    lines = [
        "=" * 60,
        "        MEDIRAG ASSISTANT — CHAT HISTORY",
        f"        Generated: {datetime.now().strftime('%B %d, %Y %I:%M %p')}",
        "=" * 60,
        ""
    ]
    for msg in messages:
        role = "You" if msg["role"] == "user" else "MediRAG"
        time = msg.get("timestamp", "")
        lines.append(f"[{time}] {role}:")
        lines.append(msg["content"])
        lines.append("-" * 40)
        lines.append("")
    return "\n".join(lines)


def _as_json(messages: list) -> str:
    export = {
        "title": "MediRAG Assistant Chat History",
        "generated_at": datetime.now().isoformat(),
        "total_messages": len(messages),
        "messages": messages
    }
    return json.dumps(export, indent=2)


def _as_markdown(messages: list) -> str:
    lines = [
        "# 🏥 MediRAG Assistant — Chat Report",
        f"**Generated:** {datetime.now().strftime('%B %d, %Y at %I:%M %p')}",
        "",
        "---",
        ""
    ]
    for msg in messages:
        role = "🧑 You" if msg["role"] == "user" else "🏥 MediRAG"
        time = msg.get("timestamp", "")
        lines.append(f"### {role}   _{time}_")
        lines.append("")
        lines.append(msg["content"])
        lines.append("")
        lines.append("---")
        lines.append("")
    lines.append("*Report generated by MediRAG Assistant*")
    return "\n".join(lines)