import streamlit as st
import json
from datetime import datetime


def render_history_download():

    st.markdown("""
    <p style="color:#7eb3d8; font-size:0.88rem; font-weight:600; margin-bottom:10px;">
        💾 Download Chat History
    </p>
    """, unsafe_allow_html=True)

    # ✅ Bug fix 1: "message" → "messages"
    if not st.session_state.get("messages"):
        st.markdown("""
        <p style="color:#4a5568; font-size:0.82rem; font-style:italic;">
            No chat history yet. Start a conversation first.
        </p>
        """, unsafe_allow_html=True)
        return

    messages = st.session_state.messages

    col1, col2 = st.columns(2)

    with col1:
        # ✅ Bug fix 2: "download_botton" → "download_button"
        st.download_button(
            label="📝 TXT",
            data=_as_txt(messages),
            file_name=f"medirag_chat_{_now()}.txt",
            mime="text/plain",
            use_container_width=True
        )

    with col2:
        st.download_button(
            label="📦 JSON",
            data=_as_json(messages),
            file_name=f"medirag_chat_{_now()}.json",
            mime="application/json",
            use_container_width=True
        )

    st.download_button(
        label="📄 Markdown Report",
        data=_as_markdown(messages),
        file_name=f"medirag_report_{_now()}.md",
        mime="text/markdown",
        use_container_width=True
    )

    st.markdown(f"""
    <p style="color:#4a5568; font-size:0.78rem; margin-top:6px;">
        {len(messages)} message(s) in history
    </p>
    """, unsafe_allow_html=True)


# ─── Formatters ───────────────────────────────────────────────────────────────

def _now() -> str:
    return datetime.now().strftime("%Y%m%d_%H%M%S")


def _as_txt(messages: list) -> str:
    lines = [
        "=" * 60,
        "        MEDIRAG ASSISTANT — CHAT HISTORY",
        f"        Generated: {datetime.now().strftime('%B %d, %Y %I:%M %p')}",
        "=" * 60,
        ""
    ]
    for msg in messages:
        role = "You" if msg["role"] == "user" else "MediRAG"
        time = msg.get("timestamp", "")
        lines.append(f"[{time}] {role}:")
        lines.append(msg["content"])
        lines.append("-" * 40)
        lines.append("")
    return "\n".join(lines)


def _as_json(messages: list) -> str:
    export = {
        "title": "MediRAG Assistant Chat History",
        "generated_at": datetime.now().isoformat(),
        "total_messages": len(messages),
        "messages": messages
    }
    return json.dumps(export, indent=2)


def _as_markdown(messages: list) -> str:
    lines = [
        "# 🏥 MediRAG Assistant — Chat report",
        f"**Generated:** {datetime.now().strftime('%B %d, %Y at %I:%M %p')}",
        "",
        "---",
        ""
    ]
    for msg in messages:
        role = "🧑 You" if msg["role"] == "user" else "🏥 MediRAG"
        time = msg.get("timestamp", "")
        lines.append(f"### {role}   _{time}_")
        lines.append("")
        lines.append(msg["content"])
        lines.append("")
        lines.append("---")
        lines.append("")
    lines.append("*Report generated by MediRAG Assistant*")
    return "\n".join(lines)